version: '2'
services:
  db:
    ports:
      - 5432:5432
  backend:
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=1
      - ALLOWED_HOST=0.0.0.0
    ports:
      - 8000:8000