# Generated by Django 2.1.4 on 2019-01-24 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 1, 24, 14, 57, 47, 299894, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
