# Generated by Django 2.1.4 on 2019-01-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_ad_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='ad',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
