# Generated by Django 2.1.4 on 2019-01-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_auto_20190124_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
